# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  solution: '**/*.sln'
  solutionName: 'CostAccounting'

steps:

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: build
    arguments: '--configuration $(buildConfiguration)'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: $(solutionName).Web.Angular/ClientApp
    verbose: false

- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    workingDir: $(solutionName).Web.Angular/ClientApp
    verbose: false
    customCommand: 'run build'

- task: DotNetCoreCLI@2
  displayName: 'Publish Solution'
  inputs:
    command: publish
    publishWebProjects: false
    projects: $(solution)
    arguments: '-c $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy: yummymoneytest'
  inputs:
    azureSubscription: 'Azure для учащихся(a2d3390a-65d3-4ab5-ae8f-bcde01e26873)'
    appType: webAppLinux
    WebAppName: yummymoneytest
    packageForLinux: '$(build.artifactstagingdirectory)/**/*.zip'
    StartupCommand: 'dotnet CostAccounting.Web.Angular.dll'
